# Generated by Django 4.0.2 on 2022-05-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionmodel',
            name='author',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='SuggestionModel',
        ),
    ]
